// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cleo.Data;

#nullable disable

namespace cleo.Migrations
{
    [DbContext(typeof(CleoDbContext))]
    [Migration("20260331183402_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("cleo.Models.AdminMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@cleo.app",
                            IsSuperAdmin = true,
                            LastActive = new DateTime(2026, 3, 31, 18, 34, 2, 475, DateTimeKind.Utc).AddTicks(6349),
                            Name = "Admin",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ava@cleo.app",
                            IsSuperAdmin = true,
                            LastActive = new DateTime(2026, 3, 31, 18, 34, 2, 475, DateTimeKind.Utc).AddTicks(6352),
                            Name = "Ava",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hensy@cleo.app",
                            IsSuperAdmin = true,
                            LastActive = new DateTime(2026, 3, 31, 18, 34, 2, 475, DateTimeKind.Utc).AddTicks(6353),
                            Name = "Hensy",
                            Password = "password123"
                        });
                });

            modelBuilder.Entity("cleo.Models.ContentArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Nutrition",
                            Content = "Detailed analysis...",
                            PublishDate = new DateTime(2026, 3, 31, 18, 34, 2, 475, DateTimeKind.Utc).AddTicks(6467),
                            Status = "Published",
                            Title = "Focus on Iron-Rich Foods",
                            Views = 1240
                        },
                        new
                        {
                            Id = 2,
                            Category = "Exercise",
                            Content = "Detailed analysis...",
                            PublishDate = new DateTime(2026, 3, 31, 18, 34, 2, 475, DateTimeKind.Utc).AddTicks(6469),
                            Status = "Published",
                            Title = "Yoga for Cramp Relief",
                            Views = 952
                        },
                        new
                        {
                            Id = 3,
                            Category = "Science",
                            Content = "Detailed analysis...",
                            PublishDate = new DateTime(2026, 3, 31, 18, 34, 2, 475, DateTimeKind.Utc).AddTicks(6471),
                            Status = "Published",
                            Title = "Understanding LH Surge",
                            Views = 1520
                        },
                        new
                        {
                            Id = 4,
                            Category = "Health",
                            Content = "Detailed analysis...",
                            PublishDate = new DateTime(2026, 3, 31, 18, 34, 2, 475, DateTimeKind.Utc).AddTicks(6471),
                            Status = "Published",
                            Title = "Managing PMS Bloating",
                            Views = 840
                        });
                });

            modelBuilder.Entity("cleo.Models.CycleTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentCycle")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CycleTracks");
                });

            modelBuilder.Entity("cleo.Models.MoodNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MoodNotes");
                });

            modelBuilder.Entity("cleo.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
